security:
    # Configuration des encodeurs de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration du fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            form_login:
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                login_path: app_login   # Route de connexion
                check_path: app_login   # Vérifie le formulaire de connexion
                default_target_path: annonce_index  # Redirige vers la liste des annonces après la connexion
            entry_point: form_login  # Utiliser le formulaire comme point d'entrée
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Configuration des contrôles d'accès
    access_control:
        # Protéger toutes les routes commençant par /admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Autoriser l'accès à la page de connexion pour tous
        - { path: ^/login, roles: PUBLIC_ACCESS }
        # Protéger toutes les autres routes pour les utilisateurs connectés
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon